export const PARAMETROS_AUDITORIA_KEYS = [
  "toleranciaMinutos",
  "toleranciaDuplicidadeMinutos",
  "janelaPareamentoMaxMinutos",
  "intervaloIntrajornadaMinutos",
  "jornadaIntrajornadaMinutos",
  "intervaloInterjornadaMinutos",
  "pontoBritanicoDias",
  "minutosResiduaisMinutos",
  "limiteHoraExtraDiariaMinutos",
  "intervaloIntrajornadaMaxMinutos",
  "diasConsecutivosLimite",
  "limiteBancoHorasPositivoMinutos",
  "limiteBancoHorasNegativoMinutos",
  "recorrenciaRiscoLimite",
];
