export {
  analisarAnomaliasPonto,
  DEFAULT_AUDITORIA_PONTO_PARAMS,
  DEFAULT_AUDITORIA_PONTO_EVENTOS_IGNORADOS,
  DEFAULT_AUDITORIA_PONTO_EVENTOS_SEM_MARCACAO_OK,
  AUDITORIA_PONTO_MOTOR_VERSION,
} from "./core/motor.js";

export { REGRAS_AUDITORIA_PONTO_META } from "./config/regras.js";
