/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaudePreventivaRouteImport } from './routes/saude-preventiva'
import { Route as Nr1RouteImport } from './routes/nr-1'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const SaudePreventivaRoute = SaudePreventivaRouteImport.update({
  id: '/saude-preventiva',
  path: '/saude-preventiva',
  getParentRoute: () => rootRouteImport,
} as any)
const Nr1Route = Nr1RouteImport.update({
  id: '/nr-1',
  path: '/nr-1',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nr-1': typeof Nr1Route
  '/saude-preventiva': typeof SaudePreventivaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nr-1': typeof Nr1Route
  '/saude-preventiva': typeof SaudePreventivaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/nr-1': typeof Nr1Route
  '/saude-preventiva': typeof SaudePreventivaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/nr-1' | '/saude-preventiva'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/nr-1' | '/saude-preventiva'
  id: '__root__' | '/' | '/login' | '/nr-1' | '/saude-preventiva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  Nr1Route: typeof Nr1Route
  SaudePreventivaRoute: typeof SaudePreventivaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saude-preventiva': {
      id: '/saude-preventiva'
      path: '/saude-preventiva'
      fullPath: '/saude-preventiva'
      preLoaderRoute: typeof SaudePreventivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nr-1': {
      id: '/nr-1'
      path: '/nr-1'
      fullPath: '/nr-1'
      preLoaderRoute: typeof Nr1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  Nr1Route: Nr1Route,
  SaudePreventivaRoute: SaudePreventivaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
